### ISSUE TITLE
🐛 `kubeapilinter` plugin ignores `settings.linters.enable` with GolangCI-Lint v2

### ISSUE THREAD

**Issue by camilamacedo86** [JoelSpeed/kal#110]
#### Environment
- **GolangCI-Lint version:** v2.1.6
- **Kube API Linter:** built and used as `.so` plugin
- **Execution:** via `make lint` or `golangci-lint run`
- **Expected:** Only the `requiredfields` rule should be run
- **Actual:** All default rules are executed (e.g. `commentstart`, `optionalorrequired`, etc.)

---

#### `.golangci.yml` Example

```yaml
version: "2"
linters:
  default: none
  enable:
    - kubeapilinter
  settings:
    custom:
      kubeapilinter:
        path: "./bin/kube-api-linter.so"
        description: "Kube API Linter plugin"
        original-url: "sigs.k8s.io/kube-api-linter"
        settings:
          linters:
            enable:
              - requiredfields
          lintersConfig: {}
```

---

#### Command

```bash
golangci-lint run
```

---

#### Result

Even though only `requiredfields` is enabled, the linter still reports violations for:
- `commentstart`
- `optionalorrequired`
- `statusoptional`
- etc.

---

#### Summary

It appears that the plugin does **not respect** the configured `settings.linters.enable` list, and always runs the full rule set.

Please clarify:
- Is `settings.linters.enable` expected to work in plugin mode with v2.x?
- If not, what is the recommended way to configure and restrict rules?

Thanks!

**Comment by pmalek** [comment]
I believe what you need to make this work is to first disable all the linters and then enable the ones that you actually want:

```
version: "2"
linters:
  default: none
  enable:
    - kubeapilinter
  settings:
    custom:
      kubeapilinter:
        type: module
        settings:
          linters:
            disable:
              - "*"
            enable:
              - jsontags
              - ....
```
